import { createContext, useState } from "react";

export const CarContext = createContext();

export default function CarProvider({ children }) {
  const [cars, setCars] = useState([
    {
    id: 1,
    no: "ADD3455",
    make: "Toyota",
    model: "Corolla",
    image: "Toyota - Corolla.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    doors: 4,
    description: "A reliable and fuel-efficient sedan, perfect for city driving and long trips.",
    features: ["Air Conditioning", "Bluetooth", "Backup Camera"],
    price_per_day: 50,
    availability_status: "Not Available",
    condition: "Excellent",
    services: "Oil Change - 2025-10-01",
  },
  {
    id: 2,
    no: "CAD2189",
    make: "Honda",
    model: "Corolla",
    image: "Honda - Civic.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Manual",
    doors: 4,
    description: "Sporty design with efficient fuel economy and comfortable interior.",
    features: ["Cruise Control", "Touchscreen Display", "ABS Brakes"],
    price_per_day: 55,
    availability_status: "Available",
    condition: "Excellent",
    services: "Full Service - 2025-09-18",
  },
  {
    id: 3,
    no: "KFD4592",
    make: "Nissan",
    model: "Sunny",
    image: "Nissan - Sunny.jpg",
    seats: 4,
    fuel: "Diesel",
    transmission: "Automatic",
    doors: 4,
    description: "Spacious and comfortable sedan ideal for family travel.",
    features: ["Rear Parking Sensors", "Power Steering", "USB Charger"],
    price_per_day: 48,
    availability_status: "Available",
    condition: "Good",
    services: "Tire Rotation - 2025-09-05",
  },
  {
    id: 4,
    no: "BGA9983",
    make: "Suzuki",
    model: "Swift",
    image: "car4.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    doors: 4,
    description: "Compact and stylish hatchback, easy to maneuver in traffic.",
    features: ["Smart Key Entry", "Touchscreen Audio", "Reverse Camera"],
    price_per_day: 45,
    availability_status: "Available",
    condition: "Excellent",
    services: "Battery Check - 2025-10-10",
  },
  {
    id: 5,
    no: "DHA5560",
    make: "Hyundai",
    model: "Elantra",
    image: "car5.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    doors: 4,
    description: "A stylish sedan offering smooth handling and great comfort.",
    features: ["Sunroof", "Auto Climate Control", "Apple CarPlay"],
    price_per_day: 60,
    availability_status: "Available",
    condition: "Excellent",
    services: "Brake Service - 2025-08-30",
  },
  {
    id: 6,
    no: "PGA1123",
    make: "Kia",
    model: "Sportage",
    image: "car6.jpg",
    seats: 5,
    fuel: "Diesel",
    transmission: "Automatic",
    doors: 4,
    description: "A powerful SUV designed for both city comfort and off-road reliability.",
    features: ["4WD", "Rear Camera", "LED Headlights"],
    price_per_day: 80,
    availability_status: "Available",
    condition: "Very Good",
    services: "Engine Tune-Up - 2025-09-12",
  },
  {
    id: 7,
    no: "HCB6721",
    make: "BMW",
    model: "320i",
    image: "car7.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    doors: 4,
    description: "Luxury performance sedan with premium interior and advanced tech.",
    features: ["Leather Seats", "Navigation", "Adaptive Cruise Control"],
    price_per_day: 120,
    availability_status: "Available",
    condition: "Excellent",
    services: "Transmission Service - 2025-09-01",
  },
  {
    id: 8,
    no: "GFA9988",
    make: "Mercedes-Benz",
    model: "C-Class",
    image: "car8.jpg",
    seats: 4,
    fuel: "Petrol",
    transmission: "Automatic",
    doors: 4,
    description: "Elegant and smooth luxury sedan with great comfort and power.",
    features: ["Panoramic Sunroof", "Memory Seats", "Auto Parking Assist"],
    price_per_day: 130,
    availability_status: "Available",
    condition: "Excellent",
    services: "Detailing - 2025-10-02",
  },
  {
    id: 9,
    no: "LDA8881",
    make: "Tesla",
    model: "Model 3",
    image: "car9.jpg",
    seats: 5,
    fuel: "Electric",
    transmission: "Automatic",
    doors: 4,
    description: "Electric sedan offering incredible performance and zero emissions.",
    features: ["Autopilot", "Glass Roof", "Fast Charging"],
    price_per_day: 150,
    availability_status: "Available",
    condition: "Excellent",
    services: "Software Update - 2025-09-25",
  },
  {
    id: 10,
    no: "MGA7642",
    make: "Jeep",
    model: "Compass",
    image: "car10.jpg",
    seats: 5,
    fuel: "Diesel",
    transmission: "Manual",
    doors: 4,
    description: "Rugged SUV built for adventure and long-distance comfort.",
    features: ["4x4 Drive", "Hill Assist", "Touchscreen Navigation"],
    price_per_day: 95,
    availability_status: "Available",
    condition: "Very Good",
    services: "Suspension Check - 2025-09-10",
  },
  ]);

  return (
    <CarContext.Provider value={{ cars, setCars }}>
      {children}
    </CarContext.Provider>
  );
}
